# ??? ?? ??? ??? (2? ??????? ?, ??? 256)
log4j2.asyncLoggerRingBufferSize=262144
# ?? ?? ??
# Yield  : CPU? ????? ?? (?? ??)
# Sleep  : CPU? ???? ?? ??
# Block  : ?? ? ? ??? ???
log4j2.asyncLoggerWaitStrategy=Yield